chore: include peer id in batch download logs (#7407)
**Motivation**

We've seen a lot of batch download errors when trying to sync a node
from far back on devnet-5
```
Jan-27 16:07:08.044[sync]          verbose: Batch download error id=Finalized, startEpoch=97, status=Downloading - Missing blobSidecars for blockSlot=3104 with blobKzgCommitmentsLen=9 blobSidecars=6
Error: Missing blobSidecars for blockSlot=3104 with blobKzgCommitmentsLen=9 blobSidecars=6
```
but from the logs it's hard to tell which peer actually sent the invalid
response and logs might get mixed up if we request data from multiple
peers at the same time.

**Description**

Include peer id in batch download logs. I opted to only include short
peer id (eg. `peer=16...UNpy88`) as this should be sufficient to see to
which request it belongs and based on that determine the client.