fix: only use proposer lookahead from state if epoch is post fulu (#7939)
Need to make sure we only run this if state is upgrade to fulu


Currently is causes spec tests to fail
```
 FAIL   spec-minimal  test/spec/presets/transition.test.ts > fulu/transition/core/pyspec_tests > fulu/transition/core/pyspec_tests/transition_with_voluntary_exit_right_before_fork
TypeError: Cannot read properties of undefined (reading 'getAll')
 ❯ EpochCache.afterProcessEpoch ../state-transition/src/cache/epochCache.ts:655:84
 ❯ processSlotsWithTransientCache ../state-transition/src/stateTransition.ts:251:28
 ❯ stateTransition ../state-transition/src/stateTransition.ts:109:15
 ❯ testFunction test/spec/presets/transition.test.ts:57:19
     55|         for (let i = 0; i < meta.blocks_count; i++) {
```